### ISSUE TITLE
<storyItem> vs <item>

### ISSUE THREAD

**Issue by bevand10** [bbc/mosromgr#11]
https://github.com/bbc/mosromgr/blob/409f303b306e1a775f0177dc2410e232516621ae/mosromgr/mostypes.py#L267

Decide /quickly/ if we should be departing from the mos protocol spec here, before we get too many (any) customers that rely on the schema of this document.

**Comment by bennuttall** [comment]
As per #12, I think it best we preserve the `roCreate` structure, which includes `<item>` tags within `<story>` tags.
