### ISSUE TITLE
Maintaining <storyBody>

### ISSUE THREAD

**Issue by bevand10** [bbc/mosromgr#12]
https://github.com/bbc/mosromgr/blob/409f303b306e1a775f0177dc2410e232516621ae/mosromgr/mostypes.py#L261

Decide if we should depart from the mos protocol convention in `roStorySend` where the following is used:

```
<roStorySend>
 <storyBody>
  <p>
  <p>
  <storyItem></storyItem>
  <p>
  <storyItem></storyItem>
 </storyBody>
</roStorySend>
```

We currently flatten to to `<story><item>...</item></story>`

By flattening, we depart from the mos convention for stories, and also make final.xml less easy to comprehend from a structural perspective, where `<p>` and `<storyItem>` are truly children of  `<storyBody>`, not peers of, for example, `<storySlug>`.

**Comment by bennuttall** [comment]
I've been back-and-forth on this a good few times now. Yesterday I made the change that would preserve the `<storyBody>` tag but I had forgotten that a `roCreate` file can have items in stories from the start, and they're not within a body, they're siblings of `<storyID>` and `<storySlug>` so that requires altering the structure of a `roCreate` file simply by loading it. I think it's best if we keep roCreate structured the way we find it.

I'm going to stash these changes just in case, but while addressing the tests I found it to be a lot more complex.

**Comment by bevand10** [comment]
I guess the point about a roStorySend is it is that specific message that brings structure to the story contents, not the basic shell/outline that's presented in a roCreate. StoryBody is designed to replace that basic outline.


```
     <storyBody>
         <storyPresenter>Suzie</storyPresenter>
         <storyPresenterRR>10</storyPresenterRR>
         <p>
            <pi> Smile </pi>
         </p>
         <p> Good Evening, I'm Suzie Humpries </p>
         <storyPresenter>Chet </storyPresenter>
         <storyPresenterRR>12</storyPresenterRR>
         <p> - and I'm Chet Daniels, this is the 5PM news on Monday November 5th.</p>
         <p>First up today - a hotel fire downtown</p>
         <storyItem>
            <itemID>1</itemID>
            <itemSlug>Hotel Fire vo</itemSlug>
            <objID>M000705</objID>
            <mosID>testmos</mosID>
            <itemEdStart>0</itemEdStart>
            <itemEdDur>800</itemEdDur>
            <itemUserTimingDur>310</itemUserTimingDur>
            <macroIn>c01/l04/dve07</macroIn>
            <macroOut>r00</macroOut>
            <mosExternalMetadata>
               <mosScope>PLAYLIST</mosScope>
               <mosSchema>http://MOSA4.com/mos/supported_schemas/MOSAXML2.08</mosSchema>
               <mosPayload>
                  <Owner>SHOLMES</Owner>
                  <transitionMode>2</transitionMode>
                  <transitionPoint>463</transitionPoint>
                  <source>a</source>
                  <destination>b</destination>
               </mosPayload>
            </mosExternalMetadata>
         </storyItem>
         <p>...as you can see, the flames were quite high. </p>
      </storyBody>
```

**Comment by bennuttall** [comment]
As I said above, I think it's best if we keep roCreate structured the way we find it. It's working well now and we're able to access the script easily.
